#!/bin/sh
FILES="file.txt"
case $1 in
#start
	s) pgrep entr > /dev/null && killall entr;  echo -e "${FILES[@]}" | sort | entr pdfmom file.txt > file.pdf 2> /dev/null &
	;;
#edit
	e) sed 's/#.*//;/^$/d;/^case/,$d;s/\\n/\
/g;/echo/,$d;s/FILES="//;s/"//' .tracker > temp && vim temp &&
		send=$(sed 's/file.txt/file.txt"/' temp | awk '{printf "%s\\n", $0}' | sed 's/"\\n/"/;s/^/FILES="/') &&
		echo $send > temp && sed "2d" .tracker > temp2 
		sed '1r temp' temp2 > temp3 
		rm temp temp2 
		chmod +x temp3
		mv temp3 .tracker
		pgrep entr > /dev/null && ./.tracker s || pdfmom file.txt > file.pdf 2> /dev/null 
	;;
#List files
	l) sed 's/#.*//;/^$/d;/^case/,$d;s/\\n/\
/g;/echo/,$d;s/FILES="//;s/"//' .tracker;;
#generate pdf
	g) pdfmom file.txt > file.pdf 2> /dev/null ;;
#initiate file tracking
i) [ -e "$2" ] && pdfname=$(printf $2 | cut -d'.' -f1); sed "/#initiate/d;s/file.txt/$2/g;s/file.pdf/$pdfname.pdf/" .tracker > temp  && mv temp .tracker && sh .tracker e || echo "file does not exist";;
esac
